- id: '1614388656844'
  alias: Motion-activated Bathroom
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 42
      motion_entity: binary_sensor.hms_bathroom_motion
      light_target:
        area_id: bathroom
