#################################################################
## Home Assistant Core
#################################################################
homeassistant:
  customize: !include custom/custom.yaml
  customize_glob: !include custom/custom_global.yaml
  packages: !include_dir_named packages/

config:
system_health:
updater:
  reporting: false
discovery:
image:
stream:
http:
dhcp:
history:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
map:
sun:
frontend:
  themes: !include_dir_merge_named themes/
logger:
  default: warning
logbook:
  exclude:
    entities:
      - script.bedroom_filament_change
#media_source:
mobile_app:
person:
#ssdp:
#tag:
timer:
webhook:
zeroconf:
zone:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-battery-entity-row/battery-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-github-entity-row/github-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/entity-attributes-card/entity-attributes-card.js
      type: module
    - url: /hacsfiles/state-attribute-element/state-attribute-element.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/select-list-card/select-list-card.js
      type: module
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-media-art-background/media-art-background.js
      type: module
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /hacsfiles/lovelace-thermostat-dark-card/thermostat-dark-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/button-text-card/button-text-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/lovelace-light-with-profiles/light-with-profiles.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: module

# Text to speech
tts:
  - platform: google_translate

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: template
    sensors:
      living_room_volume:
        friendly_name: "Living Room Volume"
        value_template: "{{ ( state_attr('media_player.living_room', 'volume_level') * 100 ) | round(0) }}"
        unit_of_measurement: "%"
