#################################################################
## Home Assistant Core
#################################################################
homeassistant:
  unit_system: metric
  time_zone: "Europe/London"
  external_url: !secret externalURL
  internal_url: "http://homeassistant.local:8123"
  allowlist_external_dirs:
    - "/config/cache"
  allowlist_external_urls:
    - "http://octopi.local"
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
  customize: !include custom/custom.yaml
  customize_glob: !include custom/custom_global.yaml
  packages: !include_dir_named packages/

config:
cloud:
system_health:

discovery:
dhcp:
ssdp:
zeroconf:

image:
stream:
http:
browser:

map:
sun:

#media_source:
mobile_app:
person:
#tag:

webhook:

updater:
  reporting: true
  include_used_components: true

zone: !include custom/zones.yaml
automation: !include custom/automations.yaml
script: !include_dir_merge_list custom/scripts/
scene: !include_dir_merge_list custom/scenes/

counter:
timer:
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
group:

history:
logger:
  default: warning
logbook:
recorder:
  commit_interval: 60
  db_url: !secret mariaDBsocket
  purge_keep_days: 90
  exclude:
    entities:
      - sensor.date
    entity_globs:
      - sensor.*_volume
      - sensor.*_warmth
      - sensor.*_brightness

      - sensor.esp_signal_*
      - sensor.esp_uptime_*
      - sensor.github_*
      - sensor.prusa_mk3s_*

      - sensor.john_lumleys_i*_distance
      - sensor.john_lumleys_i*scended
      - sensor.john_lumleys_i*_location
      - sensor.john_lumleys_i*_steps

      - switch.esp_restart_*

      - input_number.*_brightness_maximum
      - input_number.*_brightness_minimum
      - input_number.*_warmth_maximum
      - input_number.*_warmth_minimum
      - input_number.*_transition_maximum
      - input_number.*_transition_minimum
      - input_number.*_transition_current
      - input_number.*_transition_off
  include:
    domains:
      - alarm_control_panel
      - binary_sensor
      - camera
      - climate
      - device_tracker
      - media_player
      - person
      - sensor
      - switch
      - sun

      - timer
      - input_number
      - input_boolean
      - input_select
      - input_text
    entities:
      - sensor.bedroom_lamps_brightness
      - sensor.living_room_lamps_brightness

frontend:
  themes: !include_dir_merge_named themes/
lovelace:
  mode: yaml
  resources:
    - url: "https://fonts.googleapis.com/css?family=Oxygen"
      type: css
    - url: "https://fonts.googleapis.com/css?family=Oxygen+Mono"
      type: css
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-github-entity-row/github-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/select-list-card/select-list-card.js
      type: module
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/battery-state-card/battery-state-card.js
      type: module
    - url: /hacsfiles/lovelace-media-art-background/media-art-background.js
      type: module
    - url: /hacsfiles/github-flexi-card/github-flexi-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/button-text-card/button-text-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/lovelace-light-with-profiles/light-with-profiles.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
      type: module
    - url: /hacsfiles/lovelace-badge-card/badge-card.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-paper-buttons-row/paper-buttons-row.js
      type: module

  dashboards:
    ioios-admins:
      mode: yaml
      filename: dashboards/admins/home.yaml
      title: Admin View
      icon: mdi:account-plus
      show_in_sidebar: true
      require_admin: true
    ioios-hidden:
      mode: yaml
      title: Fuck
      icon: mdi:account-minus
      show_in_sidebar: false
      filename: dashboards/hidden/home.yaml

sensor:
  - platform: template
    sensors:
      living_room_volume:
        friendly_name: "Living Room Volume"
        value_template: "{{ ( state_attr('media_player.living_room', 'volume_level') * 100 ) | round(0) }}"
        unit_of_measurement: "%"
