input_number:
  bedroom_brightness_maximum:
    name: Bedroom Brightness Maximum
    min: 1
    max: 100
    initial: 50
    mode: slider
    icon: mdi:white-balance-sunny
    unit_of_measurement: "%"

  bedroom_brightness_minimum:
    name: Bedroom Brightness Minimum
    min: 0
    max: 99
    initial: 40
    mode: slider
    icon: mdi:white-balance-iridescent
    unit_of_measurement: "%"

  bedroom_transition_maximum:
    name: Bedroom Transition Maximum
    min: 1
    max: 60
    initial: 4
    mode: slider
    icon: mdi:clock-out
    unit_of_measurement: "s"

  bedroom_transition_minimum:
    name: Bedroom Transition Minimum
    min: 0
    max: 20
    initial: 1
    mode: slider
    icon: mdi:clock-in
    unit_of_measurement: "s"

  bedroom_transition_off:
    name: Bedroom Transition To Off
    min: 1
    max: 1800
    initial: 10
    mode: slider
    icon: mdi:clock-end
    unit_of_measurement: "s"

  bedroom_transition_current:
    name: Bedroom Transition To Off
    min: 0
    max: 1800
    initial: 10
    mode: box
    icon: mdi:clock-fast
    unit_of_measurement: "s"

input_boolean:
  bedroom_filament_animation:
    name: Bedroom Filament Animation Boolean
    initial: off
    icon: mdi:play-speed

  bedroom_filament_animation_editing:
    name: Bedroom Filament Animation Edit Mode Boolean
    initial: off
    icon: mdi:cogs

automation:
  - id: "1613786483628"
    alias: Bedroom Animation
    description: ""
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_filament_animation
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedroom_filament_animation_editing
      - service: script.bedroom_filament_loop
        data_template:
          brightness_max: "{{ states('input_number.bedroom_brightness_maximum') | int }}"
          brightness_min: "{{ states('input_number.bedroom_brightness_minimum') | int }}"
          transition_max: "{{ states('input_number.bedroom_transition_maximum') | int }}"
          transition_min: "{{ states('input_number.bedroom_transition_minimum') | int }}"
    mode: single

  - id: "161376532628"
    alias: Bedroom Animation Off
    description: Switch off animation with input_boolean
    trigger:
      - platform: state
        entity_id: input_boolean.bedroom_filament_animation
        from: "on"
        to: "off"
    condition: []
    action:
      - service: script.turn_off
        data:
          entity_id: script.bedroom_filament_change
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.bedroom_filament_animation_editing
      - delay: "1"
      - service: script.bedroom_filament_off
        data_template:
          transition_off: "{{ states('input_number.bedroom_transition_off') | int }}"
    mode: single

  - id: "1613798339792"
    alias: Bedroom Brightness Conformity
    description: Ensures min stays below max
    trigger:
      - platform: template
        value_template:
          "{{ (states('input_number.bedroom_brightness_minimum') | int
          ) > (states('input_number.bedroom_brightness_maximum') | int )}}"
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          value: '{{ (states("input_number.bedroom_brightness_maximum")  | int ) - 1 }}'
        entity_id: input_number.bedroom_brightness_minimum
    mode: single

  - id: "1619626439791"
    alias: Bedroom Transition Conformity
    description: Ensures min stays below max
    trigger:
      - platform: template
        value_template: "{{ states('input_number.bedroom_transition_minimum') > states('input_number.bedroom_transition_maximum')}}"
    condition: []
    action:
      - service: input_number.set_value
        data_template:
          value: '{{ (states("input_number.bedroom_transition_maximum")  | int ) - 1 }}'
        entity_id: input_number.bedroom_transition_minimum
    mode: single

script:
  bedroom_filament_off:
    description: "Turn Off Bedroom Filament Bulbs"
    fields:
      transition_off:
        description: "Off Transition Time in Seconds"
        example: "10"
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: "light.bedroom_filament_1"
          brightness: "0"
          transition: "{{ transition_off | int }}"
      - service: light.turn_on
        data_template:
          entity_id: "light.bedroom_filament_2"
          brightness: "0"
          transition: "{{ transition_off | int }}"
      - service: light.turn_on
        data_template:
          entity_id: "light.bedroom_filament_3"
          brightness: "0"
          transition: "{{ transition_off | int }}"
      - service: light.turn_on
        data_template:
          entity_id: "light.bedroom_filament_4"
          brightness: "0"
          transition: "{{ transition_off | int }}"

  bedroom_filament_loop:
    description: "Loop Bedroom Filament Bulbs"
    fields:
      brightness_max:
        description: "Maximum Random Brightness"
        example: "90"
      brightness_min:
        description: "Minimum Random Brightness"
        example: "5"
      transition_max:
        description: "Maximum Transition Time in Seconds"
        example: "5"
      transition_min:
        description: "Minimum Transition Time in Seconds"
        example: "1"
    sequence:
      - alias: "Repeat the sequence UNTIL the conditions are true"
        repeat:
          sequence:
            - service: input_number.set_value
              data_template:
                entity_id: input_number.bedroom_transition_current
                value: "{{ range( transition_min, transition_max ) | random }}"
            - service: script.bedroom_filament_change
              data_template:
                brightness_max: "{{ brightness_max }}"
                brightness_min: "{{ brightness_min }}"
                transition_secs: "{{ states('input_number.bedroom_transition_current') | int }}"
            - delay:
                milliseconds: 100
          until:
            - condition: state
              entity_id: input_boolean.bedroom_filament_animation
              state: "off"

  bedroom_filament_change:
    description: "Randomly Change Bedroom Filament Bulbs"
    fields:
      brightness_max:
        description: "Maximum Random Brightness %"
        example: "90"
      brightness_min:
        description: "Minimum Random Brightness %"
        example: "5"
      transition_secs:
        description: "Transistion Time in Seconds"
        example: "2"
    sequence:
      - service: light.turn_on
        target:
          entity_id: "light.bedroom_filament_1"
        data_template:
          brightness_pct: "{{ range( brightness_min, brightness_max ) | random }}"
          transition: "{{ range( 0 , transition_secs ) | random }}"
      - service: light.turn_on
        target:
          entity_id: "light.bedroom_filament_2"
        data_template:
          brightness_pct: "{{ range( brightness_min , brightness_max ) | random }}"
          transition: "{{ range( 0 , transition_secs ) | random }}"
      - service: light.turn_on
        target:
          entity_id: "light.bedroom_filament_3"
        data_template:
          brightness_pct: "{{ range( brightness_min , brightness_max ) | random }}"
          transition: "{{ range( 0 , transition_secs ) | random }}"
      - service: light.turn_on
        target:
          entity_id: "light.bedroom_filament_4"
        data_template:
          brightness_pct: "{{ range( brightness_min , brightness_max ) | random }}"
          transition: "{{ range( 0 , transition_secs ) | random }}"
      - delay:
          seconds: "{{ transition_secs | int }}"
