substitutions:
  boardPlatform: ESP8266
  boardName: d1_mini
  
  devicename: bedroom_detect
  deviceUpper: Bedroom Detect

<<: !include ../esphomeCommon/header.yaml
<<: !include ../esphomeCommon/api.yaml
  
switch:
  - platform: restart
    name: "ESP Restart ${deviceUpper}"
    
sensor:
  - platform: wifi_signal
    name: ESP Signal ${deviceUpper}
    update_interval: 60s

  - platform: uptime
    name: ESP Uptime ${deviceUpper}
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    id: ${devicename}_switch
    pin:
      number: TX
      inverted: true
      mode: INPUT_PULLUP
    <<: !include ../esphomeCommon/lightswitchBedroom.yaml
    
  - platform: gpio
    pin: D0
    name: "PIR: ${deviceUpper}"
    device_class: motion
    on_press:
      then:
        - light.turn_on:
            id: ${devicename}_neopixel
            brightness: 50%
            red: 30%
            green: 80%
            blue: 70%
            effect: "Knight Rider"
    on_release:
      then:
        - light.turn_off:
            id: ${devicename}_neopixel
light:
  - platform: neopixelbus
    type: GRB
    pin: RX
    num_leds: 3
    id: ${devicename}_neopixel
    name: "${deviceUpper} Ring"
    effects:
      - addressable_rainbow:
          name: Rainbow
      - addressable_color_wipe:
          name: Colour Wipe
      - addressable_scan:
          name: Knight Rider
      - addressable_twinkle:
      - addressable_fireworks:
      - addressable_random_twinkle:
          name: Occasional Twinkle
          twinkle_probability: 1%
          progress_interval: 50ms
      - automation:
          name: Alarm Sequence
          sequence:
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 100%
                green: 0%
                blue: 0%
            - delay: 400ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 0%
                green: 0%
                blue: 0%
            - delay: 200ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 100%
                green: 0%
                blue: 0%
            - delay: 400ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 0%
                green: 0%
                blue: 0%
            - delay: 200ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 100%
                green: 0%
                blue: 0%
            - delay: 400ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 0%
                green: 0%
                blue: 0%
            - delay: 200ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 100%
                green: 100%
                blue: 100%
            - delay: 100ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 0%
                green: 0%
                blue: 100%
            - delay: 200ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 100%
                green: 100%
                blue: 100%
            - delay: 100ms
            - light.addressable_set:
                id: ${devicename}_neopixel
                red: 0%
                green: 0%
                blue: 0%
            - delay: 200ms