
sensor:
  - platform: season
  - platform: time_date
    display_options:
      - "date_time_iso"

  - platform: template
    sensors:
      date_weekday:
        friendly_name: "Date: Weekday"
        value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A') }}"
      date_date:
        friendly_name: "Date: String"
        value_template: >-
          {% set day = now().strftime("%-d") %}
          {%- if day | int == 1 or day | int == 21 or day | int == 31 -%}
            {{ day }}st
          {%- elif day | int == 2 or day | int == 22 -%}
            {{ day }}nd
          {%- elif day | int == 3 or day | int == 23 -%}
            {{ day }}rd
          {%- else -%}
            {{ day }}th
          {%- endif %}
      date_month:
        friendly_name: "Date: Month String"
        value_template: >-
          {% set month_full_name = now().strftime("%B") %}
          {{ month_full_name }}
      date_time_24:
        friendly_name: "Date: 24h Time"
        value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%H:%M') }}"
      date_time_12:
        friendly_name: "Date: 12h Time"
        value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M %p') }}"
      date_full_string:
        friendly_name: "Date: Full String"
        value_template: "{{ states('sensor.date_weekday') }}, {{ states('sensor.date_string') }}"