input_select:
  debug_mode:
    name: Debug Mode
    icon: mdi:bug-check-outline
    options:
      - "Off"
      - Lights
      - Climate
      - Mobile App
      - Motion
    initial: "Off"

input_boolean:
  mode_notify_printers:
    name: "Notifications: Printers"
    icon: mdi:printer-3d-nozzle-alert-outline
    initial: on

  mode_override_circadian:
    name: "Override: Circadian Lighting"
    icon: mdi:white-balance-sunny
    initial: off

  event_updating_circadian:
    name: "Event: Updating Circadian Lighting"
    icon: mdi:white-balance-sunny
    initial: off

  service_refresh_ha:
    name: "Refresh Lovelace & Themes"
    icon: mdi:reload
    initial: off

  service_reload_ha:
    name: "Reload HA Core & Services"
    icon: mdi:reload-alert
    initial: off

  service_restart_ha:
    name: "Restart HA"
    icon: mdi:power-standby
    initial: off

  service_in_depth:
    name: "More Depth of Detail"
    icon: mdi:magnify-plus
    initial: off

sensor:
  - platform: uptime
    name: Time Online

  - platform: websocket_api

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
      - type: load_1m

automation:
  - alias: Reload Frontend
    description: Refresh Lovelace & Themes
    trigger:
      - platform: state
        entity_id: input_boolean.service_refresh_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - service: lovelace.reload_resources
      - service: frontend.reload_themes
      - service: input_boolean.turn_off
        entity_id: input_boolean.service_refresh_ha
    mode: single

  - alias: Reload HA Core
    description: Reload The Core
    trigger:
      - platform: state
        entity_id: input_boolean.service_reload_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - service: homeassistant.reload_core_config
      - service: input_boolean.turn_off
        entity_id: input_boolean.service_reload_ha
    mode: single

  - alias: Restart HA
    description: Restart Home Assistant
    trigger:
      - platform: state
        entity_id: input_boolean.service_restart_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - delay:
          seconds: 1
      - service: input_boolean.turn_off
        entity_id: input_boolean.service_restart_ha
      - delay:
          seconds: 3
      - service: homeassistant.restart
    mode: single
