input_select:
  debug_mode:
    name: Debug Mode
    icon: mdi:bug-check-outline
    options:
      - "Off"
      - Lights
      - Climate
      - Mobile App
      - Motion
    initial: "Off"

input_boolean:
  mode_notify_printers:
    name: "Notifications: Printers"
    icon: mdi:printer-3d-nozzle-alert-outline
    initial: on

  mode_override_circadian:
    name: "Override: Circadian Lighting"
    icon: mdi:white-balance-sunny
    initial: off

  event_updating_circadian:
    name: "Event: Updating Circadian Lighting"
    icon: mdi:white-balance-sunny
    initial: off

  service_refresh_ha:
    name: "Refresh Lovelace & Themes"
    icon: mdi:reload
    initial: off

  service_reload_ha:
    name: "Reload HA Core & Services"
    icon: mdi:reload-alert
    initial: off

  service_restart_ha:
    name: "Restart HA"
    icon: mdi:power-standby
    initial: off

  service_in_depth:
    name: "More Depth of Detail"
    icon: mdi:magnify-plus
    initial: off

input_text:
  core_status_display:
    name: "Status Display"
    icon: mdi:comma-circle
    initial: ""

binary_sensor:
  - platform: template
    sensors:
      core_script_running:
        friendly_name: "Core Script Running"
        value_template: >-
          {{ is_state('input_boolean.service_refresh_ha', 'on') or 
            is_state('input_boolean.service_reload_ha', 'on') }}

sensor:
  - platform: uptime
    name: Time Online

  - platform: websocket_api

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_use
      - type: last_boot
      - type: load_1m

script:
  core_refresh_ha:
    alias: Refreshing Core
    description: "Refreshing Lovelace resources and custom themes"
    sequence:
      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Lovelace Resources"

      - service: lovelace.reload_resources

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Lovelace Themes"
      - service: frontend.reload_themes

  core_reload_ha:
    alias: Reloading Core
    description: "Reload core config and all reloadable domains"
    sequence:
      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Scenes"
      - service: scene.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Templates"
      - service: template.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Groups"
      - service: group.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Timers"
      - service: timer.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Thermostats"
      - service: generic_thermostat.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Persons"
      - service: person.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Zones"
      - service: zone.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Input Booleans"
      - service: input_boolean.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Input Selects"
      - service: input_select.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Input Texts"
      - service: input_text.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Input Numbers"
      - service: input_number.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Input Datetimes"
      - service: input_datetime.reload

automation:
  - alias: Refresh HA
    description: Refresh Variables, Lovelace & Themes
    trigger:
      - platform: state
        entity_id: input_boolean.service_refresh_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.service_refresh_ha

      - service: script.core_refresh_ha

      - service: input_boolean.turn_off
        entity_id: input_boolean.service_refresh_ha
    mode: single

  - alias: Reload HA
    description: Reload The Core
    trigger:
      - platform: state
        entity_id: input_boolean.service_reload_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.service_reload_ha

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading HA Core"

      - service: homeassistant.reload_core_config

      - service: script.core_reload_ha

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Scripts"
      - service: script.reload
      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Reloading Automations"

      - service: input_boolean.turn_off
        entity_id: input_boolean.service_reload_ha
      - service: automation.reload

      - service: input_text.set_value
        data:
          entity_id: input_text.core_status_display
          value: "Successfully Reloaded"
      - delay:
          seconds: 2
    mode: single

  - alias: Restart HA
    description: Restart Home Assistant
    trigger:
      - platform: state
        entity_id: input_boolean.service_restart_ha
        from: "off"
        to: "on"
    condition: []
    action:
      - delay:
          seconds: 1
      - service: input_boolean.turn_off
        entity_id: input_boolean.service_restart_ha
      - delay:
          seconds: 3
      - service: homeassistant.restart
    mode: single
