automation:
  - alias: "John Entered Zone"
    trigger:
      - platform: zone
        entity_id:
          - person.john_lumley
        zone: zone.home
        event: enter

      - platform: zone
        entity_id:
          - person.john_lumley
        zone: zone.aird
        event: enter

      - platform: zone
        entity_id:
          - person.john_lumley
        zone: zone.lsha_yard
        event: enter

      - platform: zone
        entity_id:
          - person.john_lumley
        zone: zone.co_op
        event: enter
    action:
      - service: persistent_notification.create
        data:
          message: "John: {{ trigger.zone.name }}"
          title: "Entered Zone"
